# Generated by Django 5.2.1 on 2025-07-08 23:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faces', '0002_update_authorized_face_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='authorizedface',
            unique_together={('user', 'name')},
        ),
        migrations.RemoveField(
            model_name='authorizedface',
            name='image_url',
        ),
    ]
