# Generated by Django 5.2.1 on 2025-07-14 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingChoking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_type', models.CharField(choices=[('Choking', 'Choking'), ('NonChoking', 'NonChoking')], max_length=15)),
                ('image_url', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'training_choking',
            },
        ),
        migrations.CreateModel(
            name='TrainingFall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_type', models.CharField(choices=[('Fall', 'Fall'), ('NonFall', 'NonFall')], max_length=10)),
                ('image_url', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'training_fall',
            },
        ),
        migrations.CreateModel(
            name='TrainingFire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_type', models.CharField(choices=[('Fire', 'Fire'), ('NonFire', 'NonFire')], max_length=10)),
                ('image_url', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'training_fire',
            },
        ),
        migrations.CreateModel(
            name='TrainingResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_type', models.CharField(choices=[('fire', 'Fire'), ('choking', 'Choking'), ('fall', 'Fall'), ('violence', 'Violence')], max_length=10)),
                ('accuracy', models.FloatField()),
                ('loss', models.FloatField()),
                ('success', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'training_result',
            },
        ),
        migrations.CreateModel(
            name='TrainingViolence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_type', models.CharField(choices=[('Violence', 'Violence'), ('NonViolence', 'NonViolence')], max_length=15)),
                ('image_url', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'training_violence',
            },
        ),
    ]
